FROM gcr.io/distroless/static-debian13:nonroot

LABEL org.opencontainers.image.source="https://github.com/FrostWalk/pipeline-alert"
LABEL org.opencontainers.image.description="GitLab pipeline failure alert server"

COPY server /server

EXPOSE 8080
ENV HOST=0.0.0.0
ENV PORT=8080
ENV GIN_MODE=release

ENTRYPOINT ["/server"]
