#!/bin/sh
set -e

case "$1" in
configure)
	if command -v deb-systemd-helper >/dev/null 2>&1; then
		deb-systemd-helper unmask pipeline-horn-client.service || true
		deb-systemd-helper enable pipeline-horn-client.service || true
		deb-systemd-helper start pipeline-horn-client.service || true
	fi
	;;
esac

#DEBHELPER#

exit 0
