#!/bin/sh
set -e

case "$1" in
remove|deconfigure)
	if command -v deb-systemd-helper >/dev/null 2>&1; then
		deb-systemd-helper stop pipeline-horn-client.service || true
		deb-systemd-helper disable pipeline-horn-client.service || true
		deb-systemd-helper mask pipeline-horn-client.service || true
	fi
	;;
esac

#DEBHELPER#

exit 0
